steps:
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']
  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', 'build']
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'build']
  - name: python
    entrypoint: python
    args:
    - '-m'
    - 'twine'
    - 'upload'
    - '--repository-url'
    - 'https://us-python.pkg.dev/gapbatch/pythontesting/'
    - 'dist/*'