steps:
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']
  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', 'build']
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'build']
artifacts:
     pythonPackages:
     - repository: 'https://us-python.pkg.dev/REPOSITORY/pythontesting/sample'
        paths: ['dist/*'] 
